### ISSUE TITLE
It costs nothing to buy a restricted weapon 

### ISSUE THREAD

**Issue by ElieDeloumeau** [schwarper/cs2-advanced-weapon-system#1]
My config is :
```
["weapon_awp"]
WeaponQuota = { 1 = 0, 4 = 1, 8 = 2 }
```

And players are refunded when they buy AWP (tested on non admin players)

Is there a refund without removing the weapon or did I miss something?
https://github.com/schwarper/cs2-advanced-weapon-system/blob/main/src/event/event.cs#L122

**Comment by schwarper** [comment]
@ElieDeloumeau 
Can you use latest version and feedback please?
